import React, { useState } from 'react';
import ScheduleTable from '../Tables/ScheduleTable';
import { ScheduleEntry } from '../Tables/ScheduleTable';
import DefaultLayout from '../../layout/DefaultLayout';
import Breadcrumb from '../../components/Breadcrumbs/Breadcrumb';

const ScheduleInput: React.FC = () => {
  const [scheduleData, setScheduleData] = useState<ScheduleEntry[]>([
    {
      date: '1',
      day: '土',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '2',
      day: '日',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '3',
      day: '月',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '4',
      day: '火',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '5',
      day: '水',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '6',
      day: '木',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '7',
      day: '金',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '8',
      day: '土',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '9',
      day: '日',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '10',
      day: '月',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '11',
      day: '火',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '12',
      day: '水',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '13',
      day: '木',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '14',
      day: '金',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '15',
      day: '土',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '16',
      day: '日',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '17',
      day: '月',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '18',
      day: '火',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '19',
      day: '水',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '20',
      day: '木',
      isHoliday: true,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
      notes: '春分の日',
    },
    {
      date: '21',
      day: '金',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '22',
      day: '土',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '23',
      day: '日',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '24',
      day: '月',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '25',
      day: '火',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '26',
      day: '水',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '27',
      day: '木',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '28',
      day: '金',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '29',
      day: '土',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '30',
      day: '日',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '',
      plannedEnd: '',
      plannedPickup: false,
      plannedReturn: false,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
    {
      date: '31',
      day: '月',
      isHoliday: false,
      isAbsent: false,
      plannedStart: '09:00',
      plannedEnd: '17:00',
      plannedPickup: true,
      plannedReturn: true,
      actualStart: '',
      actualEnd: '',
      actualPickup: false,
      actualReturn: false,
    },
  ]);

  const handleScheduleChange = (newSchedule: ScheduleEntry[]) => {
    setScheduleData(newSchedule);
  };
  return (
    <DefaultLayout>
      <Breadcrumb pageName="Input Schedule" />
      <ScheduleTable
        scheduleData={scheduleData}
        onScheduleChange={handleScheduleChange}
      />
    </DefaultLayout>
  );
};

export default ScheduleInput;
